 #pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    liftPot,        sensorNone)
#pragma config(Sensor, in2,    gyro,           sensorGyro)
#pragma config(Sensor, in3,    leftFrontLine,  sensorLineFollower)
#pragma config(Sensor, dgtl1,  stashSonar,     sensorSONAR_cm)
#pragma config(Sensor, dgtl3,  touch,          sensorTouch)
#pragma config(Sensor, dgtl4,  frontTouch,     sensorTouch)
#pragma config(Sensor, I2C_1,  backRightDriveEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  backLeftDriveEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           middleLeftDrive, tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port2,           backLeftDrive, tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port3,           frontLeftDrive, tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port4,           leftLift,      tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           leftIntake,    tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port6,           backRightDrive, tmotorVex393HighSpeed, openLoop, reversed, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port7,           frontRightDrive, tmotorVex393HighSpeed, openLoop, reversed)
#pragma config(Motor,  port8,           rightLift,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port9,           rightIntake,   tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port10,          middleRightDrive, tmotorVex393HighSpeed, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)

// Include modified competition includes file
#include "competition_includes.c"

// Include modules
#include "UserControl.c"
#include "ArcadeDrive.c"
#include "Motors.c"
#include "MotorLuts.c"
#include "Auton.c"
#include "Lcd.c"
#include "Measure.c"
#include "LiftControl.c"
#include "Debug.c"

// Include third-party libraries
#include "GyroLib.c"

void pre_auton()
{
  // Stop all running tasks when the mode is switched
  bStopTasksBetweenModes = true;

  // Initialize the modules that require it
  MotorLutsInit();
  MotorsInit();
  DriveInit();
  LiftInit();
  AutonInit();
  // DriveInitGyro();
  GyroInit(gyro);

  // Let the autonomous be set using the LCD
  StartTask(LcdSetAuton);
}

task autonomous()
{
  DriveSetDeltaSettingLimits(-256, 256);

  // Reset lift control in case it is currently trying to move the arm
  LiftControlReset();

  // Unreflect the right drive in case it is reflected
  DriveUnreflectRight();

  // Start all the required tasks
  StartTask(Debug);
  StartTask(MotorsUpdate);
  StartTask(LiftControl);

  // Run the selected autonomous routine
  AutonRun();
}

task usercontrol()
{
  DriveSetDeltaSettingLimits(-70, 70);

  LiftControlReset();
  DriveUnreflectRight();

  StartTask(Debug);
  StartTask(UserControl);
  StartTask(MotorsUpdate);
  StartTask(Measure);

  while (true)
    wait1Msec(1000);
}
